version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  app:
    logging: *default-logging
    image: aarondewes/umbrui:main
    volumes:
      - ${APP_DATA_DIR}/screenshots:/usr/screenshots
      - ${APP_DATA_DIR}/../../tor/data/web/hostname:/usr/tor_hostname
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_IP: $BITCOIN_IP
      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
  screen:
    logging: *default-logging
    image: aarondewes/umbrui-renderer:main
    volumes:
      - ${APP_DATA_DIR}/screenshots:/usr/screenshots
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    depends_on:
      - app

